//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Candidate
    {
        //[Required(ErrorMessage ="Enter CandidateID")]
      //  [RegularExpression("([0-9]){6}", ErrorMessage ="Enter 6 number ID")]
        public string Candidate_ID { get; set; }

  //      [Required(ErrorMessage ="Enter Password")]
    //    [RegularExpression("^.{8,12}$", ErrorMessage = "Enter Password upto 8 to 12 characters")]
        public string Password { get; set; }

//        [Required(ErrorMessage ="Enter Candidate Name")]
        public string Name { get; set; }

        //[Required(ErrorMessage ="Enter Contact number")]
        //[DataType(DataType.PhoneNumber,ErrorMessage ="Contact number")]
        public string Mobile_no { get; set; }

      //  [Required(ErrorMessage ="Enter City")]
        public string City { get; set; }

    //    [Required(ErrorMessage ="Enter State")]
        public string State { get; set; }

  //      [Required(ErrorMessage ="Enter Email Address")]
//        [DataType(DataType.EmailAddress,ErrorMessage ="Enter Valid Email Address")]
        public string Email_id { get; set; }

        //[Required(ErrorMessage = "Please Enter AadharID")]
        //[RegularExpression("^([0-9]){4}\\s([0-9]){4}\\s([0-9]){4}$", ErrorMessage = "Enter Valid AadharID")]
        public string Aadhar_Id { get; set; }

        public string Party_id { get; set; }

        //[Required(ErrorMessage = "Enter Valid BirthDate")]
        public string DOB { get; set; }

        //[Required(ErrorMessage ="Enter Your Party Logo")]
        //[DataType(DataType.ImageUrl , ErrorMessage ="Upload Picture")]
        public string Image { get; set; }

        //[Required(ErrorMessage ="Enter Candidate Position")]
        public string Position { get; set; }

        
        public string Vote { get; set; }
    
        public virtual Party Party { get; set; }

        public HttpPostedFileBase ImageFile2 { get; set; }
    }
}
