//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Voter
    {

        public string VoterId { get; set; }

        //[Required(ErrorMessage = "Please Enter AadharID")]
        //[RegularExpression("^([0-9]){4}\\s([0-9]){4}\\s([0-9]){4}$", ErrorMessage = "Enter Valid AadharID")]
        public string AadharID { get; set; }

        //[Required(ErrorMessage = "Please Enter Name")]
        public string Name { get; set; }

        //[Required(ErrorMessage = "Please Enter Password")]
        //[RegularExpression("^.{8,12}$", ErrorMessage = "Enter Password upto 8 to 12 characters")]
        public string Password { get; set; }

        //[Required(ErrorMessage = "Please Enter Email")]
        //[EmailAddress(ErrorMessage = "Enter valid E-mail Address")]
        public string Email { get; set; }

        //[Required(ErrorMessage = "Please Enter Phone number")]
        //[RegularExpression("^([0-9]){10}$", ErrorMessage = "Enter valid Phone number")]
        public string Mobile_no { get; set; }

        //[Required]
        //[DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "{0:dd/mm/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DOB { get; set; }

        //[Required(ErrorMessage = "Please Enter City")]
        public string City {get; set;}

        //[Required(ErrorMessage = "Please Enter State")]
        public string State { get; set; }

        public string Image { get; set; }
        public string Role { get; set; }

        
        public Nullable<bool> isVoted { get; set; }
        
        public Nullable<bool> isAllowed { get; set; }

        
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
